[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/_disabled"   # for√ßa o Netlify a ignorar netlify/functions

[dev]
  command    = "npm run dev:vite"
  targetPort = 5000
  port       = 8888
  publish    = "dist"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
